---
- name: setup web server
  hosts: eec2-13-127-198-57.ap-south-1.compute.amazonaws.com
  become: yes
  tasks:
    - name: installing apache httpd service
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: start and enable httpd service
      service:
        name: apache2
        state: started
        enabled: yes
